#!/bin/bash

read gee
echo $gee 

for i in {1..22}
do
plink --vcf /Users/aisha/Desktop/KUserver/UKBioBank/ukb22418_c${i}_b0_v2.vcf.gz  --geno 0.2 --hwe 0.001 --indep-pairwise 50 5 0.2 --mind 0.2 --extract ${gee}snps.txt --keep-fam pancreas/pancreas_downsampled.txt --make-bed --recode --out ${gee}/ch${i}
done

for i in ${gee}/plinkFiles/*bed
do
echo $i | cut -f 1 -d '.' >> allfiles.txt #| cut -f 3 -d '/'  >> allfiles.txt
done

# plink --merge-list allfiles.txt --make-bed --out ${gee}_Merged
mkdir ${gee}/plinkFiles
mv ${gee}/ch* ${gee}/plinkFiles