#!/bin/bash

input="all_codes.txt"
while IFS= read -r line
do
    #echo "$line"
    mails=$(echo $line | tr "_" "\n")

    # Set comma as delimiter
    IFS='_'

    #Read the split words into an array based on comma delimiter
    read -a disease <<< "$line"
    ./codes/run ${disease[0]} ${disease[1]}
    echo "----------------------------"
done < "$input"

    ./codes/Plink_runMe